### ISSUE TITLE
Documentation issues 

### ISSUE THREAD

**Issue by rjha-splunk** [splunk/splunk-connect-for-syslog#1693]
Please don't close and use this to report your documentation issues:
e.g. 
https://splunk.github.io/splunk-connect-for-syslog/1566/gettingstarted/quickstart_guide/

**Comment by ehlo550** [comment]
I think this information is not reflected in the documentation but helps tremendously:
https://splunk-usergroups.slack.com/archives/CNV918JCQ/p1648658161334779?thread_ts=1647621045.564949&cid=CNV918JCQ

for any vendor/product source
`_nix_syslog can be appended to route the fall through to the proper index`

 I used this in splunk_metadata.csv for routing to a different index
 `    vmware_vsphere_nix_syslog,index,virtualization
`

**Comment by ehlo550** [comment]
code block for timezone is broken:
https://splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/#fix-timezone

**Comment by mstopa-splunk** [comment]
> code block for timezone is broken: https://splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/#fix-timezone

fixed in https://github.com/splunk/splunk-connect-for-syslog/commit/d421c385e6c41204cc346bc7c671f3da07559cdf

**Comment by mstopa-splunk** [comment]
> I think this information is not reflected in the documentation but helps tremendously: https://splunk-usergroups.slack.com/archives/CNV918JCQ/p1648658161334779?thread_ts=1647621045.564949&cid=CNV918JCQ
> 
> for any vendor/product source `_nix_syslog can be appended to route the fall through to the proper index`
> 
> I used this in splunk_metadata.csv for routing to a different index ` vmware_vsphere_nix_syslog,index,virtualization`

True, it can be useful when current parsers don't process new types of messages from a given vendor. In this situation one can add to `/opt/sc4s/env_file` for example:
`SC4S_LISTEN_TESTING_TEST_UDP_PORT=1515`

and then events coming through `1515/udp` will get `vendor=testing` and `product=`test`. If these are rfc compliant messages and no parser catches them, they will be also parsed as `class=nix_syslog`.  And because of that records like `testing_test_nix_syslog,index,main` will correctly redirect them like described [here](https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#log-path-overrides-of-index-or-metadata).

However, it's rather a hack than a solution to document. For situations when vendor messages are not parsed as documented please contact Splunk support or open a fix/feat request so we can update parsers.
