### ISSUE TITLE
SC4S: Can’t recognize netapp:fas

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1725]
Request for netapp:fas format

Detail: Podman 3.0.1
SC4S: v2.30.0
Index file: netapp_ontap,index,main

Rsyslog recognize the events as “sourcetype = netapp:fas” (refer to netapp_Prod_screen.JPG), but SC4S put into “sourcetype = sc4s:fallback” (refer to netapp_Dev_screen.JPG).

Use below sample echo during the test (Company relevant filtered off)

_echo "2022-06-24T04:08:11+00:00 test_sample.com test_sever: test_sever: 00000016.019e5dc4 1f1457c9 Fri Jun 24 2022 02:59:50 +05:30 [kern_audit:info:1667] 8503e80000839b68 :: test_severa:ontapi :: 10.0.0.1:52905 :: test_severa:bmcpatrol :: perf-object-get-instances :: Success: " > /dev/udp/10.198.212.246/514

echo "2022-06-24T04:08:18+00:00 test_sample.com test_sever: test_sever: 00000018.02989ce0 1e913313 Fri Jun 24 2022 03:02:15 +05:30 [kern_audit:info:1667] 8503e80000845775 :: test_severb:ontapi :: 10.0.0.1:52798 :: test_severb:.admin.001 :: <netapp version='1.0' xmlns='http://www.netapp.com/filer/admin' nmsdk_version='9.5' nmsdk_platform='Windows Server 2012 R2' nmsdk_language='Java'><perf-object-instance-list-info-iter><objectname>nfsv4:node</objectname><max-records>1000</max-records><desired-attributes><instance-info><name/><uuid/></instance-info></desired-attributes></perf-object-instance-list-info-iter></netapp>^M  :: Pending: " > /dev/udp/10.198.212.246/514_

attached together with
fallback_contain.txt - Contain in the Fallback folder for above test
netapp.zip - pcap for for above test

[netapp.zip](https://github.com/splunk/splunk-connect-for-syslog/files/8973175/netapp.zip)
[fallback_contain.txt](https://github.com/splunk/splunk-connect-for-syslog/files/8973176/fallback_contain.txt)
![netapp_Dev_screen](https://user-images.githubusercontent.com/84378190/175463350-f05867ed-7623-43c5-ba9e-969c88f11ea0.JPG)
![netapp_Prod_screen](https://user-images.githubusercontent.com/84378190/175463358-9edb85ea-53da-4f6a-b99b-7a36eaaa55de.JPG)

**Comment by rjha-splunk** [comment]
Looking into this.

**Comment by rjha-splunk** [comment]
it will be added to the sprint of enhancement.

**Comment by Jo-Ng** [comment]
@rjha-splunk Any expectation the release day? 
What actions could take as interim while wait for release? Any expectation the release day?

**Comment by rjha-splunk** [comment]
we don’t have a date yet, we will review the logs and keep you posted as soon as we will have the release date.

**Comment by mateuszpierzchala-splunk** [comment]
@Jo-Ng are you able to extract the rsyslog filter that sets the correct sourcetype?

**Comment by Jo-Ng** [comment]
@mateuszpierzchala-splunk 
I use below command, I do able to see the Pri=13 on the Splunk Portal and the output go direct to fallback.

**echo "2022-08-02T05:57:11+00:00 test_sample.com Jotest_sever_1.4: test_sever: 00000016.019e5dc4 1f1457c9 Fri Jun 24 2022 02:59:50 +05:30 [kern_audit:info:1667] 8503e80000839b68 :: test_severa:ontapi :: 10.0.0.1:52905 :: test_severa:bmcpatrol :: perf-object-get-instances :: Success: " > /dev/udp/10.198.212.246/514**

and here the output when I changed the JoTest_Sever_1.x at the SPlunk Portal
![netapp_sample](https://user-images.githubusercontent.com/84378190/182304156-f7a1f480-918e-492b-b5c7-164f58c8fe8e.JPG)

Attached the PCAP from echo. due to restriction  I can't upload the actual data into this Open forum. If need I could open case at Splunk Portal where data more protect, please let me know if this work,
[1760a_netapp2.zip](https://github.com/splunk/splunk-connect-for-syslog/files/9239513/1760a_netapp2.zip)

I didn't see any other Netapp sourcetype appeared maybe the netapp only send limited info for this test.

We are using Rsyslog version 7.4.10, didn't have any specific filter in place on it beside below:-

**[monitor:///apps/rsyslog/int_san_netapp_fas/*/]
sourcetype = netapp:fas
index = glm_storage
host_segment = 4
disabled = 0
whitelist = .*\.log$
blacklist = \.(gz|tar)$**

**Comment by mateuszpierzchala-splunk** [comment]
Hi, @Jo-Ng again thank you for your response. In case you send message that is missing PRI sc4s will add default PRI- the same happens when you send 'test' string, try it yourself (13 equals to a Priority value of 13 is “user-level” Facility and “Notice” Severity take a look at the [table](https://techdocs.broadcom.com/us/en/symantec-security-software/identity-security/privileged-access-manager/4-0/reference/messages-and-log-formats/syslog-message-formats/syslog-priority-facility-severity-grid.html) for reference.
On the opposite when we add some PRI to the message it is recognized as a syslog compliant message:
`echo '<134>2022-08-02T05:57:11+00:00 test_sample.com Jotest_sever_1.4: test_sever: 00000016.019e5dc4 1f1457c9 Fri Jun 24 2022 02:59:50 +05:30 [kern_audit:info:1667] 8503e80000839b68 :: test_severa:ontapi :: 10.0.0.1:52905 :: test_severa:bmcpatrol :: perf-object-get-instances :: Success: ' > /dev/udp/10.202.32.109/514`
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/106949453/182541173-b17b0417-931e-44ed-bc94-4d2c3c9da45a.png">
There is some issue for sure, I suppose with how filter is parsing the date because it suppose to look like this:
<img width="1949" alt="image" src="https://user-images.githubusercontent.com/106949453/182541390-cef97474-ba37-4479-aebb-a5cf708cc717.png">
I will look into this filter today and will try to extend it like I mentioned in one of the messages above. I would suggest to push all messages from Ontap family devices into one sourcetype- the one that is already defined. Let me know if that works for you,

**Comment by mateuszpierzchala-splunk** [comment]
Please feel free to copy this file to your `/opt/sc4s/local/config/app_parsers/syslog` folder and test it.
I tested it with message that you provided with addition of PRI:
`echo "<166>2022-08-03T07:54:12+00:00         test_sample.com Jotest_sever_1.4: test_sever: 00000019.0794c163 055b6737 Tue Jul 20 2022 11:45:58 +00:00 [kern_audit:info:2385] 8503ea0000ba6b71 :: nodea:ontapi :: 10.10.10.10:41464 :: nodea-esx:usera :: clone-create :: Error: Missing input: source-path; Missing input: volume" > /dev/udp/xxx.xxx.xxx.xxx/514`
and the effect is following: 
<img width="2018" alt="image" src="https://user-images.githubusercontent.com/106949453/182556085-313a3ea7-bc24-40ed-879f-2ba84ddd9ebd.png">

**Comment by mateuszpierzchala-splunk** [comment]
I merged this change and closing the issue. If you still need some help with custom change you can reach me on slack group or by email (mpierzchaa@splunk.com).
Thank you.
