### ISSUE TITLE
CROND program going to wrong index

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#2008]
Changes made in https://github.com/splunk/splunk-connect-for-syslog/pull/1884/files started sending all logs with the program `crond` to the `sourcetype=vmware:esxlog:crond`.

While this is great if the source is an ESXi host, it's terrible for any other source sending in crond e.x. (F5). 

related https://github.com/splunk/splunk-connect-for-syslog/issues/1969

We need a way to keep the esxilog crond traffic as `sourcetype=vmware:esxlog:crond` while allowing other crond traffic to still be correctly routed to `netops` (for F5) or `osnix` (for fallback-nix_syslog)

**Comment by zyphermonkey** [comment]
I've tested removing 

```conf
or program("crond", type(string) flags(ignore-case,prefix))
```

from [app-syslog-vmware_vsphere.conf](package/etc/conf.d/conflib/syslog/app-syslog-vmware_vsphere.conf) and it does successfully allow crond to make it to `osnix` and `netops` again, but now all esxi crond traffic is going to `osnix` as well.

**Comment by bparmar-splunk** [comment]
Hi @zyphermonkey,
Could you please help us with raw messages of vmware logs having crond?

**Comment by zyphermonkey** [comment]
I believe this is also related to #2015

**Comment by zyphermonkey** [comment]
**F5 Sample**  
```
<78>May  4 10:00:01 F5-host info CROND[6551]: (root) CMD (nice -n 19 ionice -c 3 /usr/share/ts/bin/asm_logrotate)
```

**Luna HSM Sample**  
```
<78>May  3 17:54:01 lsa501 crond[25050]: (root) CMD (/usr/lunasa/bin/logDiskFull)
```

**ESXi Sample**  
```
<78>2023-05-03T21:55:00.936Z hv-p02 crond[2098597]: USER root pid 2124791 cmd /bin/hostd-probe.sh ++group=host/vim/vmvisor/hostd-probe/stats/sh
```

**Comment by ikheifets-splunk** [comment]
[here](https://github.com/splunk/splunk-connect-for-syslog/blob/main/package/etc/conf.d/conflib/syslog/app-syslog-vmware_vsphere.conf#L23) we filtering by program `crond` a standard syslog message. `crond` it's a very popular tool (much popular only tools like `sshd`) by this reason it's overriding another filters for syslog.

It's seems that for this filter we can't provide`sourcetype=vmware:esxlog:$program` for `cron`, because it's just syslog filter by program and we can only send to `nix:syslog`.

P.S. But if you really need `sourcetype=vmware:esxlog:crond` I can only propose to send traffic to another port and it will [use netsource filter with same sourcetype](https://github.com/splunk/splunk-connect-for-syslog/blob/main/package/etc/conf.d/conflib/netsource/app-netsource-vmware_vsphere.conf#L23)
