### ISSUE TITLE
Meraki App Update

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-connect-for-syslog#2088]
Please update SC4S to use the [Splunk supported meraki addon](https://splunkbase.splunk.com/app/5580) vs the [developer supported addon](https://splunkbase.splunk.com/app/3018).  Specially calling out this page https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Cisco/cisco_meraki/.

**Comment by rjha-splunk** [comment]
@mateuszpierzchala-splunk Can you please check this.

**Comment by mstopa-splunk** [comment]
Hi @satellite-no, thank you for reporting this. 

Previous SC4S Meraki parser was based on vendor product by source configuration due to its general log format. 

This recent release retains previous solution for general Meraki logs, but also introduces syslog-app and almost-syslog-app parsers with sourcetypes corresponding to the official TA whenever hostname and program values enable it.

https://github.com/splunk/splunk-connect-for-syslog/blob/main/docs/sources/vendor/Cisco/cisco_meraki.md

Please let us know in case of further issues.
