### ISSUE TITLE
SC4S forward logs to Splunk without date and hostname.

### ISSUE THREAD

**Issue by Adpafer** [splunk/splunk-connect-for-syslog#2296]
Hello,

I have rsyslog configured on my linuxPC that sends logs to SC4S and then SC4S forwards these logs to a given index. Logs received by SC4S look like this example:

<30>Dec 20 08:35:26 linuxPC dbus-daemon[533]: [system] Successfully activated service 'net.reactivated.Fprint'

but when SC4S forwards them to Splunk, Splunk receives them with no date, time and host name:

dbus-daemon[533]: [system] Successfully activated service 'net.reactivated.Fprint'

Is there any way Splunk can receive the same log ?

thanks for help, regards, pawelF

**Comment by ikheifets-splunk** [comment]
Hello, @Adpafer !

In your message: 

`<30>Dec 20 08:35:26 linuxPC dbus-daemon[533]: [system] Successfully activated service 'net.reactivated.Fprint'`

That part that you mentioned its a **message header** accroding to RFC:

`<30>Dec 20 08:35:26 linuxPC`. the next thing it's a message body - `dbus-daemon[533]: [system] Successfully activated service 'net.reactivated.Fprint'`

We parsing this header and saving this header to varibles (highlighted on screenshot) and you can make a search by this variables:

![Screenshot 2023-12-22 at 15 09 50](https://github.com/splunk/splunk-connect-for-syslog/assets/138466237/9be7389d-db92-431e-8126-563d58fcc04c)

But original message you can find [here](https://github.com/splunk/splunk-connect-for-syslog/blob/33cf5614a69797a8fd47bdafde70fe35868152d6/tests/test_f5_bigip.py#L43), it's also containing `<PRI> DATETIME HOSTNAME`


P.S. [If you really want to add this header to Splunk you can use for you custom parser can use](https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#splunk-connect-for-syslog-output-templates-syslog-ng-templates) `t_everything` instead of `t_msg_only`

**Comment by ikheifets-splunk** [comment]
@Adpafer is it clear after [my answer](https://github.com/splunk/splunk-connect-for-syslog/issues/2296#issuecomment-1867751027)? If yes, please let mw know, I will close the issue
