### ISSUE TITLE
splunk_hec_metrics.conf has incomplete url

### ISSUE THREAD

**Issue by mhaley98** [splunk/splunk-connect-for-syslog#230]
Using build from 11/27 "Docker CE + systemd single node" setup. The splunk_hec_metrics.conf url is missing the /event at the end:

[root@0a7714b1900e destinations]# grep url ./*.conf 
./splunk_hec.conf:         url("https://xxxxx.com:8088/services/collector/event")
./splunk_hec_internal.conf:         url("https://xxxxx.com:8088/services/collector/event")
./splunk_hec_metrics.conf:         url("https://xxxxx.com:8088/services/collector")

Docker logs errors:
syslog-ng[1]: Server returned with a 4XX (client errors) status code, which means we are not authorized or the URL is not found.; url='https://xxxxx.com:8088/services/collector', status_code='400', driver='d_hecmetrics#0', location='/opt/syslog-ng/etc/conf.d/destinations/splunk_hec_metrics.conf:2:5'

**Comment by mbonsack** [comment]
Actually, the HEC endpoint should default to /event if it is not explicitly specified in the URL.  Though the docs should be corrected as you note, it appears that you're getting a "400" error (and not a 404).  This means that the index is invalid -- a sign that the HEC token is not permitted to write to the specified index or, more commonly, the metrics index was never created on the HEC endpoint.

If you make the correction to the URL directly in the container (it appears you exec'd into it) you can reload the config with a "kill -1 1" command.  You can then test to see if what I said above is indeed the case.

**Comment by mhaley98** [comment]
Hi - I gave that a try and do indeed continue to see the 400 errors in the docker logs output. Is it possible to change the index that hec_metrics is using? The token I'm using has access to main so I'm guessing these are trying to go to em_metrics or another index we don't have configured. Thank you.

**Comment by mbonsack** [comment]
In this case, you'll need to configure at least _one_ metrics index (other than main, which is an event index).   You can change the indexes used by any source by "uncommenting" (you really aren't uncommenting, because it's just a CSV file) the appropriate entry in splunk_indexes.csv (in the local mounted path).  You'll see an entry in that file that looks like this:

#sc4s_metrics,index,em_metrics  

(should be the last line in the file).  Change it to

sc4s_metrics,index,<whatever index you configure for metrics>

But if you don't have a metrics index configured at all, then you might as well configure it to em_metrics so you don't have to change the csv file at all.

**Comment by mhaley98** [comment]
Thanks Mark! I configured the em_metrics index and now see the metrics in Splunk and no longer have the error messages. BTW it looks like when sending metrics through hec the "/event" at the end of the url isn't necessary:https://docs.splunk.com/Documentation/SplunkCloud/8.0.0/Data/Sendmetricstoametricsindex
Again thanks - looking forward to doing more testing with SC4S. Closing issue.
