### ISSUE TITLE
Support Cisco ACI

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#250]
Cisco ACI is Cisco's software defined networking solution. It's been around for five years, and has been deployed in thousands of medium-large datacenters.

Here is a link to the technical doc for Cisco ACI syslog:
[Technote - Cisco ACI Syslog](https://community.cisco.com/t5/data-center-documents/technote-syslog-in-the-aci-fabric/ta-p/3163966?attachment-id=99450)

Page 8 shows the exact template for the syslog message. There are several samples of syslog throughout the document (eg. pages 13 and 14), including detailed tcpdumps ( pages 138-139).

**Comment by rfaircloth-splunk** [comment]
good find this one should be fairly easy

**Comment by rfaircloth-splunk** [comment]
For the purpose of this ticket, I closed it because we have NXOS support there may be other components of the "ACI umbrella" the market glossy mentions other things like load balancing that would not be covered by the NXOS or DMM components (which we don't yet have samples for). We just need to identify the additional parts and address them as we get samples.
