### ISSUE TITLE
Feature Request: source fields

### ISSUE THREAD

**Issue by w3ttr3y** [splunk/splunk-connect-for-syslog#495]
Would there be general interest in adding fields to indicate information about the syslog receiver including:
1.  ip address
2.  protocol (udp/tcp)
3.  port

At my previous employer we embedded that information in the directory path.  My current employer has just migrated to using sd4s and we have a request to add a field to indicate tcp/udp so I wanted to see if there would be interest in having this contributed upstream (here).  

If so, I would appreciate opinions on:
1.  Should this be configurable in terms of enabling/disabling and if so how granular
2.  Field names to append to the logs

**Comment by w3ttr3y** [comment]
My current thoughts on field names would be:
sc4s_syslog_receiver_address
sc4s_syslog_receiver_protocol
sc4s_syslog_receiver_port

I'd be more than happy to consider alternatives.

**Comment by mbonsack** [comment]
Since version 1.18 (two releases ago), these fields are available:
sc4s_loghost
sc4s_proto
sc4s_destport

There is also this one:

sc4s_fromhostip

that indicates the IP address of the event (independent of the hostname).
At this time, these (and other indexed fields) are controlled globally by the variable
`SC4S_DEST_SPLUNK_INDEXED_FIELDS`

See 

https://splunk-connect-for-syslog.readthedocs.io/en/develop/configuration/#splunk-hec-destination-configuration

fpr details.
